# Generated by Django 4.0 on 2022-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=200)),
                ('title_2', models.CharField(max_length=200)),
                ('title_3', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_me/')),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('body_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when the message was sent')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_of_card', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('quote', models.TextField()),
                ('quote_author', models.CharField(max_length=100)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='work_title_image/<django.db.models.fields.CharField>')),
                ('upper_image', models.ImageField(blank=True, null=True, upload_to='work_title_image/')),
                ('first_body_image', models.ImageField(blank=True, null=True, upload_to='work_body_image/')),
                ('text_of_first_body_image', models.CharField(max_length=80)),
                ('second_body_image', models.ImageField(blank=True, null=True, upload_to='work_body_image/')),
                ('text_of_second_body_image', models.CharField(max_length=80)),
                ('third_body_image', models.ImageField(blank=True, null=True, upload_to='work_body_image/')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the work was added.')),
            ],
        ),
    ]
